
WIDTH = 8240
LENGTH = 10280
HEIGHT = 2000 # TODO: Revisar con más datos

X_RANGE = (-WIDTH / 2, WIDTH / 2)
Y_RANGE = (-LENGTH / 2, LENGTH / 2)
Z_RANGE = (0, HEIGHT)

ELBOW_WIDTH = 1330

GOAL_WIDTH = (200 /  1050) * WIDTH

SURFACE_POINTS = [
    (X_RANGE[1] - ELBOW_WIDTH, Y_RANGE[0]),
    (X_RANGE[1], Y_RANGE[0] + ELBOW_WIDTH),
    (X_RANGE[1], Y_RANGE[1] - ELBOW_WIDTH),
    (X_RANGE[1] - ELBOW_WIDTH, Y_RANGE[1]),

    (X_RANGE[0] + ELBOW_WIDTH, Y_RANGE[1]),
    (X_RANGE[0], Y_RANGE[1] - ELBOW_WIDTH),
    (X_RANGE[0], Y_RANGE[0] + ELBOW_WIDTH),
    (X_RANGE[0] + ELBOW_WIDTH, Y_RANGE[0]),
]

SURFACE_LINES = list(zip(SURFACE_POINTS, 
                         SURFACE_POINTS[1:] + [SURFACE_LINES[0]])A)
