
WIDTH = 8240
LENGTH = 10280
HEIGHT = 2000 # TODO: Revisar con más datos

X_RANGE = (-WIDTH / 2, WIDTH / 2)
Y_RANGE = (-LENGTH / 2, LENGTH / 2)
Z_RANGE = (0, HEIGHT)

ELBOW_WIDTH = 1330

SURFACE_POINTS = [
    (X_RANGE[1] - ELBOW_WIDTH, Y_RANGE[0]),
    (X_RANGE[1], Y_RANGE[0] + ELBOW_WIDTH),
    (X_RANGE[1], Y_RANGE[1] - ELBOW_WIDTH),
    (X_RANGE[1] - ELBOW_WIDTH, Y_RANGE[1]),

    (X_RANGE[0] + ELBOW_WIDTH, Y_RANGE[1]),
    (X_RANGE[0], Y_RANGE[1] - ELBOW_WIDTH),
    (X_RANGE[0], Y_RANGE[0] + ELBOW_WIDTH),
    (X_RANGE[0] + ELBOW_WIDTH, Y_RANGE[0]),
]

